### ISSUE TITLE
Feature requests for $__time() and  $__timeFilter, Create Variable, Data in time series (chart) 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [scottlepp/grafana-sqlproxy-datasource#2]
-          does it support $__time() and  $__timeFilter? if not , how can I add the dashboard time filter to my panel
-          I tried to create variable with impala DS , the query is working on the REST API  but I do not get any value back in the variable list of values

![image](https://user-images.githubusercontent.com/54800912/91962363-55998d00-ed04-11ea-93fd-e98dc35ca00e.png)

-          I can see data in table but not as time series(chart)  even after setting time as alias of the time column , you can see below same data in two panels (one with table and one as time series ) the time column in the db is timestamp

![image](https://user-images.githubusercontent.com/54800912/91962390-60ecb880-ed04-11ea-85d0-46f4ea803b8f.png)

are $__time() and  $__timeFilter supported currently?

**Comment by scottlepp** [comment]
@aengusrooneygrafana I've added macros for referencing the time range.   https://github.com/scottlepp/grafana-sqlproxy-datasource#time-macros

**Comment by scottlepp** [comment]
@aengusrooneygrafana added support for variables of type Query

**Comment by scottlepp** [comment]
@aengusrooneygrafana any column/alias named "time" will now be used as the timeseries time.
